language: groovy
jdk:
  - oraclejdk7
script: 
      - ./grailsw refresh-dependencies
      - ./grailsw test-app -echoOut -echoErr -coverage -xml
after_success:
      - ./grailsw coveralls
deploy:
    provider: heroku
    api_key: 7cf2c57e-3333-43e0-bbfa-1172c957e0d2
    app: imogram
